#!/bin/bash

# This hook runs before dependencies are installed
# We'll modify the Podfile to disable warnings-as-errors for RNFBApp

echo "EAS Hook: Preparing to disable non-modular header warnings for React Native Firebase"

# The Podfile will be generated by Expo, so we need to run this after prebuild
# This is just a placeholder - the actual modification will happen in post-install hook
